(TeX-add-style-hook "clValid"
 (lambda ()
    (LaTeX-add-bibliographies
     "ClusterRefs")
    (LaTeX-add-labels
     "sec:introduction"
     "sec:measures"
     "subsec:internal"
     "subsec:stability"
     "subsec:biological"
     "sec:clustering"
     "sec:illustration"
     "fig:internPlot"
     "fig:stabPlot"
     "fig:BHI"
     "fig:BSI"
     "fig:BHI2"
     "fig:BSI2"
     "fig:hplot"
     "sec:discussion")
    (TeX-run-style-hooks
     "Sweave"
     "gbMacros"
     "natbib"
     "round"
     "euscript"
     "mathcal"
     "relsize"
     "hyperref"
     "color"
     "graphics"
     "amsfonts"
     "amssymb"
     "amsmath"
     "latex2e"
     "art11"
     "article"
     "11pt")))

